import re
import shutil
from pathlib import Path

HEADER_COMMENT = (
    "##############################################################################\n"
    "#                                                                            #\n"
    "# This file is automatically generated by a script.                          #\n"
    "# For readable source code, please refer to the project's GitHub repository. #\n"
    "#                                                                            #\n"
    "##############################################################################\n\n"
)

PREFIX = "YAML__"

INTERNAL_TYPES = [
    "YAMLResult",
    # "YAML",
    "Token",
    "Mark",
    "Scanner",
    "Event",
    "Parser",
    "YAMLNode",
    "Composer",
    "Resolver",
    "Constructor",
    "Representer",
    "Serializer",
    "Emitter",
    "StreamWrapper",
    "Util"
]

SRC_DIR = Path("addons/miniyaml")
DIST_DIR = Path("dist/addons/miniyaml")
MAIN_FILE = "miniyaml.gd"


def process_line(line: str, patterns):
    result = []
    in_string = False
    string_char = None
    buffer = ""

    def flush_buffer():
        nonlocal buffer
        for pattern, replacement in patterns:
            buffer = pattern.sub(replacement, buffer)
        result.append(buffer)
        buffer = ""

    i = 0
    while i < len(line):
        ch = line[i]

        if ch in ("'", '"'):
            if not in_string:
                flush_buffer()
                in_string = True
                string_char = ch
                result.append(ch)
            elif string_char == ch:
                in_string = False
                string_char = None
                result.append(ch)
            else:
                result.append(ch)
        else:
            if in_string:
                result.append(ch)
            else:
                buffer += ch
        i += 1

    if buffer:
        flush_buffer()

    return "".join(result)


def process_file(src: Path, dst: Path):
    patterns = [
        (re.compile(rf"\b{name}\b"), PREFIX + name)
        for name in INTERNAL_TYPES
    ]

    with src.open("r", encoding="utf-8") as f:
        lines = f.readlines()

    processed = [
        process_line(line, patterns)
        for line in lines
    ]

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write(HEADER_COMMENT)
        f.writelines(processed)


def build_dist():
    if Path("dist").exists():
        shutil.rmtree(Path("dist"))
    DIST_DIR.mkdir(parents=True)

    for ext in ["*.gd", "*.cfg"]:
        for path in SRC_DIR.rglob(ext):
            rel = path.relative_to(SRC_DIR)
            target = DIST_DIR / rel

            if path.is_dir():
                target.mkdir(exist_ok=True)
                continue

            if path.name == MAIN_FILE:
                print(f"Processing: {rel}")
                process_file(path, target)
            else:
                shutil.copy2(path, target)

    additional_file_paths = [
        "addons/miniyaml/LICENSE",
        "doc/supported_syntax.yaml",
        "doc/dumped_supported_syntax.yaml",
    ]

    for afp in additional_file_paths:
        path = Path(afp)
        target = DIST_DIR / path.name
        shutil.copy2(path, target)

    print("✔ dist build complete")


if __name__ == "__main__":
    build_dist()
